---
title: "ST 558 Project 2"
author: "Jessica Speer"
date: "July 3, 2020"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyr)
library(caret)
library(corrplot)
library(dplyr)
library(rmarkdown)
```

## Load in and Prep Data
```{r, echo=TRUE}
#Read in data, filter according to day of week, keep relevant variables
data<-read.csv("C:\\Users\\jessi\\Documents\\ST 558\\data\\OnlineNewsPopularity.csv", header=T)
#Generate categorical outcome variable
data$sharescat[data$shares < 1400] <- 0
data$sharescat[data$shares >= 1400] <- 1
data$sharescat <- as.factor(data$sharescat)
#Create single day variable
data$day[data$weekday_is_monday==1] <- "monday"
data$day[data$weekday_is_tuesday==1] <- "tuesday"
data$day[data$weekday_is_wednesday==1] <- "wednesday"
data$day[data$weekday_is_thursday==1] <- "thursday"
data$day[data$weekday_is_friday==1] <- "friday"
data$day[data$weekday_is_saturday==1] <- "saturday"
data$day[data$weekday_is_sunday==1] <- "sunday"
#Filter according to day of week
data<-data %>% filter(day=="monday")
#Split data into training and test sets
set.seed(1)
train <- sample(1:nrow(data), size = nrow(data)*0.7)
test <- dplyr::setdiff(1:nrow(data), train)
dataTrain <- data[train, ]
dataTest <- data[test, ]
```

```{r, echo=TRUE}
#par(mfrow=c(2,2))
#hist(dataTrain$shares, col="dark blue")
#hist(dataTrain$average_token_length, col="dark blue")
#hist(dataTrain$kw_avg_avg, col="dark blue")
#hist(dataTrain$LDA_03, col="dark blue")

plot(dataTrain$shares, col="dark blue")
#plot(dataTrain$average_token_length, col="dark blue")
#plot(dataTrain$kw_avg_avg, col="dark blue")
```

```{r, echo=TRUE}
lm_fit<-train(shares ~ average_token_length + kw_avg_avg + LDA_03 + avg_negative_polarity + self_reference_avg_sharess + data_channel_is_entertainment + data_channel_is_world, data=dataTrain, method="lm")

summary(lm_fit)

#make predictions on test data
test_pred <- predict(lm_fit, newdata = dataTest)
residuals<-dataTest$shares - test_pred
summary(abs(residuals))
plot(dataTest$shares,test_pred, col="dark blue")
```


# Fit random forest
```{r, echo=T}
set.seed(16)
trctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 3)
#rf_fit <- train(sharescat ~ average_token_length + kw_avg_avg + LDA_03 + avg_negative_polarity + self_reference_avg_sharess + data_channel_is_entertainment + data_channel_is_world, data = dataTrain, method = "rf", trControl=trctrl, preProcess = c("center", "scale"))
#rf_fit
#make predictions on test data
#test_pred <- predict(rf_fit, newdata = dataTest)
#res <- confusionMatrix(test_pred, dataTest$sharescat)
#res
#misclassification rate
#1-sum(diag(res$table))/sum(res$table)
```


